// Auto-generated by FoodGuard AI Model Exporter
// This runs the trained Regression Model natively in Javascript without any backend APIs.

export function predictRisk(features: {
  rainfall_deficit_pct: number;
  temp_anomaly_c: number;
  reservoir_level_pct: number;
  area_sown_ha: number;
  yield_t_ha: number;
}): number {
  const MEANS = [28.49921804511278, 4.115037593984963, 50.06013533834586, 56890.98796992481, 2.9252631578947366];
  const SCALES = [0.014907906942676777, 2.23554660152931, 1.828444956548362, 25202.52815722353, 0.7799272946135818];
  const COEFS = [0.0051342077612788126, 5.580719780722528, -0.2744200152868651, 0.0003497056335372906, 1.3025547783937754e-05];
  const INTERCEPT = 21.678195488721805;

  const raw_features = [
    features.rainfall_deficit_pct,
    features.temp_anomaly_c,
    features.reservoir_level_pct,
    features.area_sown_ha,
    features.yield_t_ha
  ];

  let score = INTERCEPT;
  
  for (let i = 0; i < 5; i++) {
    // Standardize feature
    const scaled_feature = (raw_features[i] - MEANS[i]) / SCALES[i];
    score += scaled_feature * COEFS[i];
  }

  // Bound the score between 0 and 100
  return Math.max(0, Math.min(100, score));
}
